### ISSUE TITLE
Title formatting on long titles

### ISSUE THREAD

**Issue by Luminarys** [rekyuu/kumo-manga#2]
Currently manga titles which are too long will end up overlapping with each other and going off the screen, as can be seen here: ![](https://0x0.st/z98.png)

**Comment by rekyuu** [comment]
Attempted to fix with [`3ed8632`](https://github.com/rekyuu/kumo-manga/commit/3ed8632524197dc56c70346d64426515a6d86631#diff-ba9ea169c8e3e98c3d89754c7a57cf4a). Don't have any long titles to check myself.

**Comment by Luminarys** [comment]
Fixed.
